// patient data
export const initialFormData = {
    role: localStorage.getItem("selectedRole"),
    first_name: "",
    last_name: "",
    email: "",
    phone: "",
    password: "",
    confirm_password: "",
    date_of_birth: "",
    gender: "",
    marital_status: "",
    street_address: "",
    street_address_2: "",
    city: "",
    region: "",
    zip: "",
    country: "",
    blood_type: "",
    any_medication: "",
    additional_notes: "",
    family_doctor_name: "",
    emergency_first_name: "",
    emergency_last_name: "",
    emergency_relationship: "",
    emergency_contact: "",
    insurance_provider: "",
    insurance_id: "",
    policyholder_name: "",
    group_number: "",
};
