"""modify doctors model by removing unnecessary columns

Revision ID: 18516ed3944b
Revises: e9e0778f865d
Create Date: 2025-12-22 14:29:40.561337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18516ed3944b'
down_revision: Union[str, None] = 'e9e0778f865d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'region')
    op.drop_column('doctors', 'recovery_email')
    op.drop_column('doctors', 'zip')
    op.drop_column('doctors', 'street_address_2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('street_address_2', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('doctors', sa.Column('zip', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('doctors', sa.Column('recovery_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('doctors', sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
