"""modify doctors model by adding availability_status column

Revision ID: 683ae8590935
Revises: 18516ed3944b
Create Date: 2025-12-22 17:46:04.221618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '683ae8590935'
down_revision: Union[str, None] = '18516ed3944b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('availability_status', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'availability_status')
    # ### end Alembic commands ###
