"""modify patients table by removing extra columns

Revision ID: 7e903afb9c8a
Revises: f144579cf508
Create Date: 2025-12-18 23:18:12.612137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e903afb9c8a'
down_revision: Union[str, None] = 'f144579cf508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_notifications_id', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_column('patients', 'street_address_2')
    op.drop_column('patients', 'group_number')
    op.drop_column('patients', 'policyholder_name')
    op.drop_column('patients', 'region')
    op.drop_column('patients', 'zip')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('zip', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('policyholder_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('group_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('street_address_2', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_id', 'notifications', ['id'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'title',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
